### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by tl3shi** [tufu9441/hexo-blog#1]
我看你的blog也是host在github上的，绑定了独立域名, 
你这个是怎么实现的， github pages不是要写一个CNAME, 且repo为 username.github.com/io 才可以么?

我用了你的模板, 从 [wordpress](http://wordpress.tanglei.name) 转到 [hexo](http://www.tanglei.name)上的，期间还遇到了不少问题，还在一个一个解决中。

求指教~

**Comment by tl3shi** [comment]
还有你的source分支也不在这个库里面么? 404页面是怎么generate出来的?

**Comment by tufu9441** [comment]
我是放在阿里云商，并不是github。

**Comment by tl3shi** [comment]
酱紫啊~ 多谢~ 
hexo每次new一个post，都需要重新generate整站么? generate这个过程好慢。

**Comment by tufu9441** [comment]
是的，需要。

**Comment by tl3shi** [comment]
这个主题写得可能还是有些问题。 我generate一次需要半个小时。。 [ref](https://github.com/hexojs/hexo/issues/1769)

>
@tl3shi I cloned your repo
It took 16mins to run hexo g --debug, however if I changed the theme from maupassant to landscape, it took 16 seconds.
maupassant used 0.6s to render a post vs 0.1s to that of landsacape. Maybe you can reflect this to the author.

**Comment by tl3shi** [comment]
用这个主题半小时才OK， 换其他主题20s即可。
[my repo](https://github.com/tl3shi/hexo.tanglei.name)

有空的话，帮忙看看， 多谢。

**Comment by tufu9441** [comment]
从来没有人反映过这个问题啊，也许是你两个renderer没有安好？升级到Hexo 3.2.0试试，我现在100多篇文章每次generate只需要几秒。

**Comment by tl3shi** [comment]
你可以clone我的那个[repo](https://github.com/tl3shi/hexo.tanglei.name) 测试一下 ~ 能够稳定重现. 
确实是这样的。 :(

**Comment by tufu9441** [comment]
我试了一下还真是这样，然而我真的不知道是什么原因……

**Comment by tl3shi** [comment]
主题开发不用写 md 到 html的逻辑吧? 
只需要写从一个post中提取比如tags 分类等，然后添加class css之类的?

**Comment by tufu9441** [comment]
我也不清楚，我只是从别人那里fork过来然后自己修改的，你可以自己看看：
https://github.com/tufu9441/maupassant-hexo/
